[tools]
python = "3.10.11"
poetry = "1.8.1"

[settings]
experimental = true

[tasks.setup]
description = "Setup project"
run = [
    "mise i",
    "poetry install"
]

[tasks.fix]
description = "Check lint and Apply format"
run = [
    "ruff check . --fix",
]